- name: test
  hosts: localhost
  become: true
  serial: 1
  vars:
      test: "test"
#  vars_files:
#    - "{{ lookup('ansible.builtin.env', 'VARS_FILE') }}"
  pre_tasks: 
    - ansible.builtin.include_vars:
        file: "{{ lookup('ansible.builtin.env', 'ADDITIONAL_VARS_FILE') | default('default/vars.yml', True) }}"
  tasks:
    - name: echo
      ansible.builtin.debug:
        msg: "{{ test }}"

