- name: test
  hosts: all
  vars:
      test: "test"
  pre_tasks: 
    - ansible.builtin.include_vars:
        file: "{{ lookup('ansible.builtin.env', 'ADDITIONAL_VARS_FILE') | default('vars/default.yml', True) }}"
  tasks:
    - name: echo
      ansible.builtin.debug:
        msg: "{{ test }}"

